---
title: "Resources and FAQ"
---

Below are some resources to help with learning R.

# R

- [RStudio Cheat Sheets](https://www.rstudio.com/resources/cheatsheets/)
- [Using RStudio cheatsheet](https://www.rstudio.com/wp-content/uploads/2016/01/rstudio-IDE-cheatsheet.pdf)
- [Quick walkthrough and book for doing data analysis in R](http://r4ds.had.co.nz/index.html)
- [Software Carpentry R material](http://swcarpentry.github.io/r-novice-gapminder/)

## Basics

- [CRAN website](https://cran.r-project.org/)
- [CRAN R Reference Card](https://cran.r-project.org/doc/contrib/Short-refcard.pdf)
- [Interactive R tutorial](http://tryr.codeschool.com/)

## Data wrangling

- [Common and frequently used commands in R](http://adv-r.had.co.nz/Vocabulary.html)
- Tibble
- [Data frames in `dplyr`](https://cran.r-project.org/web/packages/dplyr/vignettes/data_frames.html)
- [Introduction to `dplyr`](https://cran.r-project.org/web/packages/dplyr/vignettes/introduction.html)
- [Cheatsheet for `dplyr` and `tidyr`](https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf)
- [Introduction to `tidyr`](https://cran.r-project.org/web/packages/tidyr/vignettes/tidy-data.html)
- [Shorter intro to `tidyr`](http://blog.rstudio.org/2014/07/22/introducing-tidyr/)
- [Regular expression symbol meaning](http://www.endmemo.com/program/R/gsub.php)
- [`dplyr` with databases in SQL and other formats](https://cran.r-project.org/web/packages/dplyr/vignettes/databases.html)
- [Merging two dataframes using `dplyr`](https://cran.r-project.org/web/packages/dplyr/vignettes/two-table.html)
- [Excellent explanation of merges and joins](http://r4ds.had.co.nz/relational-data.html)

## R Markdown

- [R Markdown site](http://rmarkdown.rstudio.com/)
- [`knitr` website](http://yihui.name/knitr/)
- [R Markdown Cheat Sheet (brief)](http://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf)
- [R Markdown more complete reference sheet](http://www.rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf)
- [Markdown basics](http://rmarkdown.rstudio.com/authoring_basics.html)
- [Code chunk options brief](http://rmarkdown.rstudio.com/authoring_rcodechunks.html)
- [Bibliographies and citations](http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html)
- [Creating HTML documents (`YAML` options)](http://rmarkdown.rstudio.com/html_document_format.html)
- [Creating Word documents (`YAML` options)](http://rmarkdown.rstudio.com/word_document_format.html)
- [Using the `captioner` package](https://cran.r-project.org/web/packages/captioner/vignettes/using_captioner.html)
- [Customization of markdown tables (`pander`)](http://rapporter.github.io/pander/)

## Other resources

- Q & A for R programming: <http://www.stackoverflow.com>
- Q & A for R statistics: <http://stats.stackexchange.com>

# Frequently asked questions (FAQ)

- Is there any computers available to use for this workshop?
    
    At this time, no there is not. You will need to bring your laptop.

- Is there any special software I need?

    Besides the *free* and *open-source* programs listed in the
    [instructions](instructions.html) page, you don't need anything else!

- What if I don't have a laptop?

    As with the question above, at this time we can't accommodate people who
    don't have access to a laptop. Learners have in the past been able to get a
    laptop from the own lab or department. One eventual goal is that we can get
    these workshops in a computer lab of sorts to remove this issue.
